spring:
  application:
    name: api-gateway

server:
  port: 8765

services-routes:
  auth-service: "http://authentication-service:8080"
  user-service: "http://user-service:8080"
  order-service: "http://order-service:8080"
  payment-service: "http://payment-service:8080"